### ISSUE TITLE
Restore database in JSON format

### ISSUE THREAD

**Issue by C0ldF0x** [timeoff-management/timeoff-management-application#436]
I was trying to upgrade the current version I'm using but it was throwing some errors and I decided then to download the current information from the platform and then try to import it.

The problem that I found was that the version that I'm using export in JSON and the latest ones accepts .csv

Is there any process to convert the file or any option to import the JSON into the latest version?

**Comment by vpp** [comment]
Hi @C0ldF0x, looks like the version you have is quite out of date. The feature of data migration between instances was retired and it did not get the track from customers.

For upgrade process I would suggest (given you use default DB option of SQLite):
* copy SQLite DB file from your LIVE installation to new location
* checkout newest version of TimeOff.Management to new location
* run `npm install` and `npm run-script db-update`

That should be enough to upgrade.

**Comment by C0ldF0x** [comment]
Thanks for the help @vpp .
I finally got time to put some work into this and I got this far:
- current version running is **v0.6.2**, in production mode and running in **Docker container**;
- was able to connect to the **MySQL** database and dump the data to a **SQL file**;
- cloned the rep to my pc and went back to **v0.6.2**;
- with that version I was able to create an **SQLite** database;
- copied the **insert statments** from the **MySQL's dump**, sorted them due to the foreign key relations and was able to insert the current data in this _new_ database;
- I was able to run in **v0.6.2** and the data was all fine, with the only exception being that I had to restore the password (I assume due to the fact that I forgot to copy the `crypto_secret `from the production instance);
- I then went back to **master** and ran `npm install` and `npm run-script db-update`;
- and here is where I'm at. Running `npm run-script db-update` throws:
```bash
> TimeOff.Management@1.0.0 db-update /home/ubuntu/timeoff/test
> node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/

/home/ubuntu/timeoff/test/node_modules/.bin/sequelize:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at Module._compile (internal/modules/cjs/loader.js:743:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TimeOff.Management@1.0.0 db-update: `node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TimeOff.Management@1.0.0 db-update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

If someone's able to help it would be great, but I'll comeback to this problem as soon as I'm able to get some time.
