### ISSUE TITLE
Application crashing with LDAP

### ISSUE THREAD

**Issue by asterisktec** [timeoff-management/timeoff-management-application#443]
I really love this program however I am getting constant crashing once I enable LDAP.

events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at LdapAuth._handleError (/home/coiadmin/timeoff-management/node_modules/ldapauth-fork/lib/ldapauth.js:185:8)
    at Client.emit (events.js:198:13)
    at Socket.onSocketError (/home/coiadmin/timeoff-management/node_modules/ldapjs/lib/client/client.js:1169:12)
    at Socket.emit (events.js:198:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TimeOff.Management@1.0.0 start: `node bin/wwww`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the TimeOff.Management@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/coiadmin/.npm/_logs/2020-09-01T15_16_19_660Z-debug.log

Any ideas? ...

**Comment by jorgarrote23** [comment]
I'm having the same problem as you
