### ISSUE TITLE
Error deploying to EC2 on AWS

### ISSUE THREAD

**Issue by WolaApplication** [timeoff-management/timeoff-management-application#503]
Hi everybody,

I am trying to deploy it on an EC2 instance and after installing all dependencies I am not able to start it. 

The error is: Please install sqlite3 package manually

Sqlite3 is installed and available on the instance. 

Running a node run-script db-update raise the following error in the same way:

`Sequelize [Node: 14.18.2, CLI: 2.5.1, ORM: 3.19.2, sqlite3: 4.2.0]

fs.js:40
} = primordials;
    ^

ReferenceError: primordials is not defined
    at fs.js:40:5
    at req_ (/home/ec2-user/timeoff-management-application/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/home/ec2-user/timeoff-management-application/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/home/ec2-user/timeoff-management-application/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! TimeOff.Management@1.0.0 db-update: `node node_modules/.bin/sequelize db:migrate --config=config/db.json --models-path=lib/model/db/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the TimeOff.Management@1.0.0 db-update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

Thanks in advance!

**Comment by blacklevel** [comment]
@WolaApplication were you ever able to fix this? I have the same error with `db-update` on Ubuntu 18.04.

**Comment by blacklevel** [comment]
FYI  - I managed to fix the `primodials`error by downgrading `graceful-fs` according to these instructions:

https://ourcodeworld.com/articles/read/1188/how-to-solve-gulp-exception-reference-error-primordials-is-not-defined-error#disqus_thread
