### ISSUE TITLE
Self host install errors

### ISSUE THREAD

**Issue by piersonjarvis** [timeoff-management/timeoff-management-application#549]
Hello, I'm trying to get this installed on a server for personal use. I've installed git, npm, node.js, and sqlite, however I keep getting errors when trying to npm install. I'm fairly new to node.js so a lot of this is going over my head. 

Below are the errors I am getting. 

npm ERR! code 1
npm ERR! path /home/timeoff/timeoff-management/node_modules/sqlite3
npm ERR! command failed
npm ERR! command sh -c -- node-pre-gyp install --fallback-to-build
npm ERR! make: Entering directory '/home/timeoff/timeoff-management/node_modules/sqlite3/build'
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c
npm ERR! make: Leaving directory '/home/timeoff/timeoff-management/node_modules/sqlite3/build'
npm ERR! Failed to execute '/usr/bin/node /usr/share/nodejs/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/timeoff/timeoff-management/node_modules/sqlite3/lib/binding/node-v108-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/timeoff/timeoff-management/node_modules/sqlite3/lib/binding/node-v108-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.11.0
npm ERR! node-pre-gyp info using node@18.7.0 | linux | x64
npm ERR! node-pre-gyp WARN Using request for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/home/timeoff/timeoff-management/node_modules/sqlite3/lib/binding/node-v108-linux-x64/node_sqlite3.node" (not found)
npm ERR! node-pre-gyp http GET https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp http 403 https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v108-linux-x64.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v108-linux-x64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for sqlite3@4.2.0 and node@18.7.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 403 status code downloading tarball https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.2.0/node-v108-linux-x64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.7.0 | linux | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.7.0 | linux | x64
npm ERR! gyp info find Python using Python version 3.10.7 found at "/usr/bin/python3"
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/timeoff/timeoff-management/node_modules/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/share/nodejs/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/include/nodejs/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/usr/include/nodejs',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/share/nodejs/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/usr/include/nodejs/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/timeoff/timeoff-management/node_modules/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@18.7.0 | linux | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! /bin/sh: 1: python: not found
npm ERR! make: *** [deps/action_before_build.target.mk:13: Release/obj/gen/sqlite-autoconf-3310100/sqlite3.c] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Linux 5.19.0-29-generic
npm ERR! gyp ERR! command "/usr/bin/node" "/usr/share/nodejs/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/home/timeoff/timeoff-management/node_modules/sqlite3/lib/binding/node-v108-linux-x64/node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=/home/timeoff/timeoff-management/node_modules/sqlite3/lib/binding/node-v108-linux-x64" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /home/timeoff/timeoff-management/node_modules/sqlite3
npm ERR! gyp ERR! node -v v18.7.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/share/nodejs/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/home/timeoff/timeoff-management/node_modules/sqlite3/lib/binding/node-v108-linux-x64/node_sqlite3.node --module_name=node_sqlite3 --module_path=/home/timeoff/timeoff-management/node_modules/sqlite3/lib/binding/node-v108-linux-x64 --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/timeoff/timeoff-management/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 5.19.0-29-generic
npm ERR! node-pre-gyp ERR! command "/usr/bin/node" "/home/timeoff/timeoff-management/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /home/timeoff/timeoff-management/node_modules/sqlite3
npm ERR! node-pre-gyp ERR! node -v v18.7.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.11.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-17T18_30_29_985Z-debug-0.log

**Comment by aamador0202** [comment]
Im having the same issue, were you able to resolve?

**Comment by AB2yz** [comment]
I had these same issues when trying to install. I'm running on Ubuntu 22.04.2 and got it working by using Node V14 and manually installing sqlite3.
These are the steps I took:

# sudo apt update
# sudo apt upgrade
# sudo apt install nodejs
# sudo apt install npm
# curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh -o install_nvm.sh
# bash install_nvm.sh
# source ~/.bash_profile
# nvm install 14.0.0
# npm install sqlite3 --save
# git clone https://github.com/timeoff-management/application.git timeoff-management
# cd timeoff-management
# npm install
# npm start

**Comment by JohannesFleischer** [comment]
@adocampo if you want to start the servoce with docker you can try [this](https://github.com/timeoff-management/timeoff-management-application/pull/531/) PR.
Worked for me. I guess a fix in main could take a while.

I somehow managed to get the second newest release to work natively, but also only once and on a secomd try it trew errors again..

**Comment by adocampo** [comment]
> @adocampo if you want to start the service with docker you can try [this](https://github.com/timeoff-management/timeoff-management-application/pull/531/) PR. Worked for me. I guess a fix in main could take a while.
> 
> I somehow managed to get the second newest release to work natively, but also only once and on a secomd try it trew errors again..

Yes, docker is building with your PR! Thank you very much!

**Comment by adocampo** [comment]
@JohannesFleischer by the way, it build but does it start?  Mine fails with
```
> TimeOff.Management@1.0.0 start
> node bin/wwww

node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module '/app/bin/wwww'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**Comment by iNaiks** [comment]
> I had these same issues when trying to install. I'm running on Ubuntu 22.04.2 and got it working by using Node V14 and manually installing sqlite3. These are the steps I took:
> 
> sudo apt update sudo apt upgrade sudo apt install nodejs sudo apt install npm curl -sL https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh -o install_nvm.sh bash install_nvm.sh source ~/.bash_profile nvm install 14.0.0 npm install sqlite3 --save git clone https://github.com/timeoff-management/application.git timeoff-management cd timeoff-management npm install npm start

Error on installing sqlite3 from rpm.


How can I create a docker instead of installing on the OS?.

**Comment by mermetbt** [comment]
@iNaiks I've created a docker image available on DockerHub https://hub.docker.com/r/aliengen/timeoff-management-application with changes that are not included in the current version available in this repository (see my PR https://github.com/timeoff-management/timeoff-management-application/pull/570)

**Comment by brandonwylescom** [comment]
I know this is somewhat an old thread now, but I have got this running with the following prerequisits

Node 14.0.0
SQLite3
Python2.7 (apt-get update;    apt-get install python2.7;    ln -s /usr/bin/python2.7 /usr/bin/python)

Follow the usual setup process
